name:                aoc2024
version:             0.1.0.0
github:              "jojonium/aoc2024"
license:             GPLv3
author:              "Joseph Petitti"
maintainer:          "joseph@petitti.org"
copyright:           "2024 Joseph Petitti"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jojonium/advent-of-code-2024#readme>

dependencies:
- base >= 4.7 && < 5
- split
- containers
- mtl
- search-algorithms

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

